name: diploma

services:
  php:
    image: php:8.3-fpm
    container_name: diploma-php
    volumes:
      - ./:/var/www/html/
    ports: ['9000:9000']

  web:
    image: nginx:alpine
    container_name: diploma-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html